apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-limit-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cluster-limit-controller
  template:
    metadata:
      labels:
        name: cluster-limit-controller
    spec:
      serviceAccountName: limitrange-controller
      containers:
        - name: cluster-limit-controller
          image: jicki/cluster-limit-controller:1.9
          command:
            - ./app/cluster-limit-controller
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "200m"
